connector_config:
  log_source: "Postgres"
database_config:
  query: "select * from TABLE_NAME where {field_name} > {initial_value} limit FETCH_LIMIT"
  field_name: somefield
  initial_value: ""
  connection_mode: jdbc
  connection_string: "jdbc:postgresql://<DATABASE_SERVER_IP>:<PORT>/<DATABASE>"
  classpath: "rdbms_jar/postgresql-42.2.9.jar"
  connection_driver: "org.postgresql.Driver"
  user: ""
  password: ""
forwarding_config:
  dst_ip: ""
  dst_port: ""
  transfer_type: udp